// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZA-yisK20F8CG31PmHezLxxTxqUbNSk',
    appId: '1:427861629573:web:4c4ee4d1a894617593a7ec',
    messagingSenderId: '427861629573',
    projectId: 'flutter-auth-dum',
    authDomain: 'flutter-auth-dum.firebaseapp.com',
    storageBucket: 'flutter-auth-dum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvIJ2c6RedTZGOUSE0Wbi3aBhCgAzYCA',
    appId: '1:427861629573:android:42790e73210d5b5c93a7ec',
    messagingSenderId: '427861629573',
    projectId: 'flutter-auth-dum',
    storageBucket: 'flutter-auth-dum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgU_4gTWY9xAPLBnpZ7xfiZquJp-19NuY',
    appId: '1:427861629573:ios:c7dc68dcb6bfb2ee93a7ec',
    messagingSenderId: '427861629573',
    projectId: 'flutter-auth-dum',
    storageBucket: 'flutter-auth-dum.appspot.com',
    iosBundleId: 'be.helha.b3q1HakemProjetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgU_4gTWY9xAPLBnpZ7xfiZquJp-19NuY',
    appId: '1:427861629573:ios:be03e84be186f2cc93a7ec',
    messagingSenderId: '427861629573',
    projectId: 'flutter-auth-dum',
    storageBucket: 'flutter-auth-dum.appspot.com',
    iosBundleId: 'be.helha.b3q1HakemProjetFlutter.RunnerTests',
  );
}
